### ISSUE TITLE
length - длина, лучше подобрать другое название

### ISSUE THREAD

**Issue by coursar** [RenatFaiz/Homeworks#12]
https://github.com/RenatFaiz/Homeworks/blob/451e18be2dec80a421b34c19b7c4e0ab6782e09b/src/homework_1/Fuel.java#L24

**Comment by RenatFaiz** [comment]
так же исправил #13, расстояние в км  #14 
ca0b5adaf7c5ccd1c7ae2c612992bd2226787ff7
