### ISSUE TITLE
На каждое ДЗ должен быть отдельный репозиторий

### ISSUE THREAD

**Issue by coursar** [RenatFaiz/Homeworks#4]

**Comment by RenatFaiz** [comment]
Я на каждое ДЗ сделал отдельный репозиторий
https://github.com/RenatFaiz/Fuel
https://github.com/RenatFaiz/Wallpapers
https://github.com/RenatFaiz/Sportmaster
И в коммитах сделал комментарии на те участки кода, которые исправил. К сожалению, сослаться на эти issue оттуда я не могу. Из-за того, что там другие репозитории. Но я отметил там Вас в тексте
